### PR TITLE
Bug fix and extension of brian2-simulation-script

### PR DESCRIPTION
**Pull request by sflin**

### CODE REVIEW

**Comment by rbodo** [comment]
Hi @sflin , 

You recently extended the brian2 backend; thank you for that. You also dropped the 0 in the v equation. I currently don't have the chance to test it myself, and have not used Brian2 in a long time. Can you explain why this change is necessary? Another user reported it as an error.

Thanks!

Bodo

**Comment by sflin** [comment]
Hi Bodo,
Die Korrektur stammt von Alpha. Er hat mir mit der Brian2-Simulation geholfen. Ich habe ihm die Mail einmal weitergeleitet und gefragt, wieso der Change nötig ist.
Liebe Grüsse
Selin

**Comment by AI-pha** [comment]
Hi @rbodo,
sorry for the late reply. I think there was an error in the pull request (in commit 544b17ce264f8ce20b581977f549ee53c6812b6b.)

What I actually wrote was (there was a typo introduced later):
`self.eqs = 'v : 1'`

`'v = : 1' ` is of course the wrong syntax and leads to an error.

We changed it in the first place, as the original code `self.eqs = 'v  = 0 : 1'`
leads to the following error, as v is initialized as a subexpression instead of a variable:
`Illegal line 'v+=w' in abstract code. Cannot write to subexpression 'v'.`

Another change that I would suggest is using keyword arguments when the NeuronGroup is created, as the order of arguments changes between versions, which led to another error in our case.
```python
        self.layers.append(self.sim.NeuronGroup(
            np.prod(layer.output_shape[1:]), model=self.eqs, method='linear',
            reset=self.v_reset,
            threshold=self.threshold,
            dt=self._dt * self.sim.ms))
```

I created a pull request #43 to fix this

**Comment by rbodo** [comment]
Great, thank you! 

I'll try to see whether this solves #39 and #40 and write a couple of unit tests for this soon.

**Pull request merged**
